# Generated by Django 6.0.4 on 2026-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liuyingauth', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='liuyingauth.userprofile', verbose_name='关注的人'),
        ),
    ]
