"""
Django settings for liuyingblog project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 日志文件存放目录
LOG_DIR = os.path.join(BASE_DIR, 'logs')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # 保留 Django 默认的日志记录器
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        # 错误日志 → logs/error/{YYYY-MM-DD}.log (WARNING 及以上)
        'file_error': {
            'level': 'WARNING',
            'class': 'liuyingblog.log_handlers.DailyFileHandler',
            'base_dir': os.path.join(LOG_DIR, 'error'),
            'backup_count': 30,
            'formatter': 'verbose',
        },
        # 信息日志 → logs/info/{YYYY-MM-DD}.log (INFO 及以上)
        'file_info': {
            'level': 'INFO',
            'class': 'liuyingblog.log_handlers.DailyFileHandler',
            'base_dir': os.path.join(LOG_DIR, 'info'),
            'backup_count': 30,
            'formatter': 'simple',
        },
    },
    'loggers': {
        # Django 框架自身的日志
        'django': {
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'INFO',
            'propagate': True,
        },
        # 你的核心业务 App 日志
        'blog': {
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'INFO',
        },
        # 认证模块 App 日志
        'liuyingauth': {
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'INFO',
        },
    },
}

# 如果 logs 文件夹不存在，则创建（开发环境防错）
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


# 加载根目录的 .env 文件
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'fallback-secret-key-for-local-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG') == 'True'

ALLOWED_HOSTS = ['43.163.232.238','www.liuying.com','liuying.com','127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'liuyingauth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'liuyingblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 添加静态文件标签
            'builtins':['django.templatetags.static']
        },
    },
]

WSGI_APPLICATION = 'liuyingblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# 静态文件加载路径
STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]
STATIC_ROOT = '/www/wwwroot/liuying/static/'
# ★ 新增：媒体文件（用户上传的文件）
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#发送邮件相关配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = '3302393536@qq.com'
EMAIL_FROM_NAME = '流萤博客'
# 从环境变量读取邮箱授权码，避免明文硬编码
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = '3302393536@qq.com'

DJANGO_MYSQL_VERSION_CHECK = False


# 显示在后台左上角的网站名称
JAZZMIN_SETTINGS_TITLE = "流萤博客管理后台"

# 隐藏 Django 默认的 "更改密码" 和 "查看站点" 按钮（可选）
JAZZMIN_SETTINGS_SHOW_CHANGE_LINK = False
JAZZMIN_SETTINGS_SHOW_VIEW_ON_SITE = False

# 日期格式的本地化
JAZZMIN_SETTINGS_DATETIME_FORMAT = 'Y-m-d H:i'


#==========================================
#★ Redis 高级配置区

#==========================================

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # 使用 1 号库，避免和其他应用冲突
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "CONNECTION_KWARGS": {
            #     "decode_responses": True,  # 自动将字节转成字符串，免去 decode 的烦恼
            # }
            "IGNORE_EXCEPTIONS": True,  # 忽略 Redis 连接错误，回退到本地缓存
        }
    }
}

#★ 将 Session 存储引擎也换成 Redis（企业级标配）
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# ==========================================
# ★ DRF 配置区
# ==========================================
REST_FRAMEWORK = {
    # 每页默认显示 10 条数据
    'PAGE_SIZE': 10,
    # 默认使用分页
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 开启自动接口文档（极其重要！）
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.AutoSchema',
}


# ==========================================
# ★ 自定义认证机制配置
# ==========================================
AUTHENTICATION_BACKENDS = [
    'liuyingauth.backends.EmailOrUsernameModelBackend',  # 优先使用我们的新规则（支持邮箱/用户名）
    'django.contrib.auth.backends.ModelBackend',         # 保留 Django 原生规则作为兜底
]


# ==========================================
# ★ Celery 配置区
# ==========================================
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/1'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
